# Generated by Django 5.0.4 on 2024-04-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя роли')),
            ],
            options={
                'verbose_name': 'Роль сотрудника',
                'verbose_name_plural': 'Роли сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', max_length=50, verbose_name='Краткое описание')),
                ('x_position', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Позиция по X для карты')),
                ('y_position', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Позиция по Y для карты')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='Последняя проверка')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='MFPColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя цвета картриджа')),
            ],
            options={
                'verbose_name': 'Цвет картриджа',
                'verbose_name_plural': 'Цвета картриджей',
            },
        ),
        migrations.CreateModel(
            name='MFPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя типа')),
            ],
            options={
                'verbose_name': 'Тип МФУ',
                'verbose_name_plural': 'Типы МФУ',
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(default='-', max_length=50, null=True, verbose_name='Отчество')),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employeerole', verbose_name='Роль сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='MFP',
            fields=[
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.equipment', verbose_name='Какое оборудование является МФУ?')),
                ('is_wb', models.BooleanField(default=False, verbose_name='Черно-белый?')),
                ('format', models.CharField(max_length=50, verbose_name='Формат печати')),
                ('colour_copy_amount', models.IntegerField(default=0, verbose_name='Количество напечатанных цветных страниц')),
                ('black_copy_amount', models.IntegerField(default=0, verbose_name='Количество напечатанных ЧБ страниц')),
                ('mfp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.mfptype', verbose_name='Тип МФУ')),
            ],
            options={
                'verbose_name': 'МФУ',
                'verbose_name_plural': 'МФУ',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.equipment', verbose_name='Какое оборудование является ПК?')),
                ('characteristics', models.TextField(verbose_name='Характеристики')),
                ('commentary', models.TextField(blank=True, default='', verbose_name='Комментарий к ПК')),
            ],
            options={
                'verbose_name': 'ПК',
                'verbose_name_plural': 'ПК',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField(verbose_name='Комментарий')),
                ('date_of_request', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('date_of_last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employeerole', verbose_name='Сотрудник')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.equipment', verbose_name='Оборудование')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.requeststatus', verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='MFPCartridge',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('storage_amount', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('page_resource', models.IntegerField(default=0, verbose_name='Ресурс страниц')),
                ('commentary', models.TextField(blank=True, default='', verbose_name='Комментарий к картриджу')),
                ('url', models.TextField(blank=True, default='', verbose_name='Ссылка на картридж для покупки')),
                ('last_change_date', models.DateTimeField(auto_now_add=True, verbose_name='Последнее обновление')),
                ('mfp_colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.mfpcolour', verbose_name='Цвет картриджа')),
                ('mfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.mfp', verbose_name='К какому МФУ картридж?')),
            ],
            options={
                'verbose_name': 'Картридж для МФУ',
                'verbose_name_plural': 'Картриджи для МФУ',
            },
        ),
    ]
