# Generated by Django 5.0.4 on 2024-04-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfpcolour',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя цвета картриджа'),
        ),
        migrations.AlterField(
            model_name='mfptype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя типа'),
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя статуса'),
        ),
    ]
