# Generated by Django 5.0.4 on 2024-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_mfpcolour_name_alter_mfptype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.CharField(default='-', max_length=50, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='-', max_length=50, verbose_name='Пароль'),
        ),
    ]
