# Generated by Django 5.0.4 on 2024-04-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_employee_login_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='commentary',
        ),
    ]
