# Generated by Django 5.0.4 on 2024-04-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_pc_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employee', verbose_name='Сотрудник'),
        ),
    ]
