# Generated by Django 5.0.4 on 2024-05-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_requests_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='FrogRestFramework/static/img', verbose_name='Изображение карты')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_in_stock',
            field=models.BooleanField(default=False, verbose_name='На складе?'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='API.map', verbose_name='На какой карте оборудование находится'),
        ),
    ]
